# This manifest file creates a PersistentVolume named 'ebs-static' using an AWS EBS volume.
    # The volume has a capacity of 20Gi and supports ReadWriteOnce access mode.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  accessModes: # Access mode for the  persistent volume
  - ReadWriteOnce # the volume can be mounted as read-write by a single node (ebs cannot be mounted to multiple nodes simultaneously)
  capacity:
    storage: 20Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0c16d3f01a6a95d6f # this volume is created by me in aws console and attaching here so the pv uses this ebs volume

# This PersistentVolume can be used by Pods in the cluster to store data persistently using the specified EBS volume.


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static # Name of the PersistentVolumeClaim
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
# This PersistentVolumeClaim requests 15Gi of storage from the 'ebs-static' PersistentVolume.
# It specifies ReadWriteOnce access mode and binds to the 'ebs-static' volume created above.

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: ebs-static-demo
    project: roboshop
spec:
  nodeSelector: # scheduling the pod to run on specific nodes
    topology.kubernetes.io/zone: us-east-1a # scheduling the pod to run in specific availability zone
  containers:
  - name: nginx
    image: nginx
    volumeMounts: # here am mounting the volume to container
    - name: persistent-storage
      mountPath: /usr/share/nginx/html # path where the volume will be mounted inside the container
  volumes: # here am creating volume to mount pvc to pod 
  - name: persistent-storage # volume name
    persistentVolumeClaim: # mounting pvc to pod
      claimName: ebs-static # pvc name

---
# to acess this application from outside the cluster we need to create service for this pod
apiVersion: v1
kind: Service 
metadata:
  name: ebs-static
  labels:
    purpose: ebs-static-demo
    project: roboshop
spec:
  type: LoadBalancer # to access outside the cluster because it exposes the service externally using a cloud provider's load balancer
  selector:
    purpose: ebs-static-demo
    project: roboshop
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port

# This Pod runs an Nginx container and mounts the EBS-backed PersistentVolumeClaim at /usr/share/nginx/html.
# The Pod is scheduled to run on nodes in the 'us-east-1c' availability zone.

# can you give me explanation for above code?
# This manifest file creates a PersistentVolume (PV), a PersistentVolumeClaim (PVC), and a Pod that uses the PVC to mount an AWS EBS volume.
# The PV named 'ebs-static' uses an existing EBS volume and provides 20Gi of storage with ReadWriteOnce access mode.
# The PVC named 'ebs-static' requests 15Gi of storage from the 'ebs-static' PV.
# Finally, a Pod named 'nginx' runs an Nginx container and mounts the PVC at /usr/share/nginx/html, allowing the container to use the EBS volume for persistent storage.
# The Pod is scheduled to run on nodes in the 'us-east-1a' availability zone using a node selector.
# The PersistentVolumeClaim ensures that the Pod has access to the required storage.
# The Nginx container will serve content from the EBS volume mounted at /usr/share/nginx/html.

# here are creating the volume to the pod and and mounting to the container inside the pod an i correct ?
# Yes, you are correct. In the provided manifest file, a PersistentVolume (PV) and a PersistentVolumeClaim (PVC) are created first.

# The PV named 'ebs-static' is backed by an AWS EBS volume, and it provides 20Gi of storage with ReadWriteOnce access mode.
# The PVC named 'ebs-static' requests 15Gi of storage from the 'ebs-static' PV.
# Then, a Pod named 'nginx' is created, which runs an Nginx container.
# Inside the Pod specification, the PVC is mounted as a volume named 'persistent-storage' at the path /usr/share/nginx/html within the Nginx container.
# This setup allows the Nginx container to use the EBS volume for persistent storage, meaning that any data written to /usr/share/nginx/html will be stored on the EBS volume and will persist even if the Pod is deleted or recreated. 
# So, in summary, the volume is created using the PVC, and it is mounted to the Nginx container inside the Pod.


