# This manifest file creates a PersistentVolume named 'ebs-static' using an AWS EBS volume.
    # The volume has a capacity of 20Gi and supports ReadWriteOnce access mode.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  accessModes: # Access mode for the  persistent volume
  - ReadWriteOnce # the volume can be mounted as read-write by a single node (ebs cannot be mounted to multiple nodes simultaneously)
  capacity:
    storage: 20Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0c16d3f01a6a95d6f # this volume is created by me in aws console and attaching here 

# This PersistentVolume can be used by Pods in the cluster to store data persistently using the specified EBS volume.


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static # Name of the PersistentVolumeClaim
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
# This PersistentVolumeClaim requests 15Gi of storage from the 'ebs-static' PersistentVolume.
# It specifies ReadWriteOnce access mode and binds to the 'ebs-static' volume created above.

# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: nginx
#   labels:
#     purpose: ebs-static-demo
#     project: roboshop
# spec:
#   nodeSelector:
#     topology.kubernetes.io/zone: us-east-1a
#   containers:
#   - name: nginx
#     image: nginx
#     volumeMounts: # docker run -v host-path:container-path
#     - name: persistent-storage
#       mountPath: /usr/share/nginx/html
#   volumes:
#   - name: persistent-storage
#     persistentVolumeClaim:
      # claimName: ebs-static
# This Pod runs an Nginx container and mounts the EBS-backed PersistentVolumeClaim at /usr/share/nginx/html.
# The Pod is scheduled to run on nodes in the 'us-east-1c' availability zone.