apiVersion: v1
kind: Pod
metadata:
  name: resources
  spec:
    containers:
      - name: nginx
        image: nginx
        resources: # soft limits
          requests:
            memory: "68Mi"
            cpu: "100m"
          limits: #hard limits
            memory: "128Mi"
            cpu: "150m" #we should extend up to this limit