apiVersion: v1
kind: Service
metadata:
  name: nginx-np # Name of the service with NodePort type
  labels:
    purpose: service-np-demo
spec:
  type: NodePort # Service type is NodePort to expose the service on a static port on each Node's IP address
  selector:
    purpose: service-np-demo
    project: roboshop
    environment: dev
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port
      

---
  apiVersion: v1
  kind: Pod
  metadata:
    name: nginx-np
    labels:
      purpose: service-np-demo
      project: roboshop
      env: dev
  spec:
    containers:
      - name: nginx
        image: nginx
        
# The Service of type NodePort is used to expose the Pod named nginx-np on a static port on each Node's IP address