apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  labels:
    purpose: service-lb-demo
spec:
  type: LoadBalancer # Service type is LoadBalancer to expose the service externally using a cloud provider's load balancer
  selector:
    purpose: service-lb-demo
    project: roboshop
    environment: dev
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port
      

---
  apiVersion: v1
  kind: Pod
  metadata:
    name: nginx-lb
    labels:
      purpose: service-lb-demo
      project: roboshop
      env: dev
  spec:
    containers:
      - name: nginx
        image: nginx
        
        # The Service of type LoadBalancer is used to expose the Pod named nginx-lb externally using a cloud provider's load balancer